-- ============================================================
-- Lean/Bridge.lean — FFI Bindings to C-- Kernel
-- Generated by lake build (do not edit manually)
-- ============================================================

-- Opaque context type (matches C BridgeContext*)
constant BridgeContextPoint : Type

-- FFI Declarations
@[extern "bridge_init"]
opaque bridgeInit : UInt64 → IO (Ptr BridgeContextPoint)

@[extern "bridge_free"]
opaque bridgeFree : Ptr BridgeContextPoint → IO Unit

@[extern "bridge_compute"]
opaque bridgeCompute : Ptr BridgeContextPoint → Int64 → IO Int64

@[extern "bridge_rewrite"]
opaque bridgeRewrite : Ptr BridgeContextPoint → Int64 → Int64 → IO Int64

@[extern "bridge_verify"]
opaque bridgeVerify : Ptr BridgeContextPoint → Int64 → IO Int32

-- ============================================================
-- High-Level Wrapper
-- ============================================================

structure BridgeCtx where
  ptr : Ptr BridgeContextPoint

def BridgeCtx.new (config : UInt64 := 0) : IO BridgeCtx := do
  let ptr ← bridgeInit config
  if ptr == 0 then
    throw (IO.userError "bridge_init returned NULL")
  pure ⟨ptr⟩

def BridgeCtx.free (ctx : BridgeCtx) : IO Unit :=
  bridgeFree ctx.ptr

def BridgeCtx.compute (ctx : BridgeCtx) (input : Int64) : IO Int64 :=
  bridgeCompute ctx.ptr input

def BridgeCtx.rewrite (ctx : BridgeCtx) (patternId : Int64) (input : Int64) : IO Int64 :=
  bridgeRewrite ctx.ptr patternId input

def BridgeCtx.verify (ctx : BridgeCtx) (theoremId : Int64) : IO Bool := do
  let result ← bridgeVerify ctx.ptr theoremId
  pure (result != 0)

-- ============================================================
-- Closed-Form Rewrite API (Lean-side dispatch)
-- ============================================================

-- SumSquares: Σ_{k=1}^n k² = n(n+1)(2n+1)/6
def sumSquaresClosedForm (n : Int64) : Int64 :=
  n * (n + 1) * (2 * n + 1) / 6

-- SumLinear: Σ_{k=1}^n k = n(n+1)/2
def sumLinearClosedForm (n : Int64) : Int64 :=
  n * (n + 1) / 2

-- SumCubes: Σ_{k=1}^n k³ = (n(n+1)/2)²
def sumCubesClosedForm (n : Int64) : Int64 :=
  let sum := n * (n + 1) / 2
  sum * sum

-- Pattern registry
def rewritePattern (ctx : BridgeCtx) (patternId : Int64) (n : Int64) : IO Int64 :=
  ctx.rewrite patternId n
